name: my_money
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>= 2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  fl_chart: ^0.62.0
  modal_bottom_sheet: ^2.1.2
  dio: ^5.3.2
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

